### ISSUE TITLE
Fix paths to executables when authenticating to Kubernetes API using CLI/K9S

### ISSUE THREAD

**Issue by anovikov-el** [edenlabllc/rmk#84]
### Description

The following config should be defined correctly (mind the command's value):

```
- name: rmk-test-develop-capi-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - -i
      - rmk-test-develop
      command: <absolute_path_to_HOME/.local/bin>/aws-iam-authenticator
      env:
      - name: AWS_PROFILE
        value: rmk-test-develop
      - name: AWS_CONFIG_FILE
        value: /Users/user/.aws/config_rmk-test-develop
      - name: AWS_SHARED_CREDENTIALS_FILE
        value: /Users/user/.aws/credentials_rmk-test-develop
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

### Steps to reproduce

Run CLI/K9S with no exported path to `~/.local/bin`.

### Expected behaviour

No error returned, authentication successful.

### Actual behaviour

Authentication failed.

### Environment info

RMK: v0.45.0+ (with the Cluster API support)
OS: any
Shell: any
Terminal: any

### Agree to the Code of Conduct

- [x] I agree to follow this project's Code of Conduct
